# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - LCAIPlayerCountTracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Verify assets directory
        run: |
          echo "Checking assets directory content:"
          ls -la assets/
          echo "Making sure assets directory exists and has correct permissions"
          mkdir -p assets
          chmod -R 755 assets

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Prepare deployment package
        run: |
          echo "Creating deployment package..."
          echo "Verifying assets directory is included..."
          if [ -d "assets" ]; then
            echo "Assets directory contents:"
            ls -la assets/
          else
            echo "Warning: assets directory not found!"
          fi
          zip -r release.zip . -x "*.git*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Verify deployment content
        run: |
          echo "Deployment package contents:"
          ls -la
          echo "Assets directory contents:"
          ls -la assets/ || echo "Warning: assets directory not found in deployment package!"

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'LCAIPlayerCountTracker'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_11A30028A2E641FDB041A1C4C28514CB }}